# This file contains values from Cookiecutter

default_context:
  project_name: "plinkliftover"
  project_description: "Awesome `plinkliftover` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "OMRF"
  license: "GNU GPL v3.0"
  version: "0.1.0"
  github_name: "milescsmith"
  email: "miles-smith@omrf.org"
